version: "3.8"

services:
  php-fpm:
    build:
      context: devops/php
      args:
        - USER_ID=1000
        - GROUP_ID=1000
        - APP_PORT=8000
        - UNAME=local
    container_name: php-fpm
    networks:
      - php-fpm
    ports:
      - "9000:8000"
    volumes:
      - ./:/app
      - ./devops/supervisor/supervisor.conf:/etc/supervisord.conf
      - ./devops/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./devops/php-fpm/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./devops/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./devops/php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./devops/scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh
    working_dir: /app
    entrypoint: ["/bin/bash", "-c", "entrypoint.sh"]

networks:
  php-fpm:
    driver: bridge